version: '3.7'
volumes:
    appdata: ~

services:
    mysql:
        platform: linux/x86_64
        image: mysql:8
        container_name: formula_points_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
            - .docker/data/test:/home/test
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            default:
                aliases:
                    - 'mysql.formula-points'
                    - 'mysql'

    phpmyadmin:
        container_name: formula_points_phpMyAdmin
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=mysql
            - PMA_USER=${MYSQL_USER}
            - PMA_PASSWORD=${MYSQL_PASSWORD}

    maildev:
        container_name: formula_points_mail
        image: maildev/maildev
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8082:80"
        restart: always

    php:
        build: .docker/php
        container_name: formula_points_php
        volumes:
            - ${SYMFONY_APP}:${WORKDIR}
            - appdata:${WORKDIR}/var/cache
            - appdata:${WORKDIR}/var/log
            - ./app/vendor:${WORKDIR}/vendor:delegated
        working_dir: ${WORKDIR}
        depends_on:
            - mysql

    nginx:
        container_name: formula_points_nginx
        build: .docker/nginx
        volumes:
            - ${SYMFONY_APP}:${WORKDIR}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - mysql
            - php
        networks:
            default:
                aliases:
                    - 'dev.formula-points'
