version: '3.9'

volumes:
    generated_files: ~
    data_storage: ~

services:
    mysql:
        image: mysql:8.0.29-oracle
        container_name: formula_points_mysql
        volumes:
            - data_storage:/var/lib/mysql
        networks:
            default:
                aliases:
                    - 'mysql.formula-points'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"


    php:
        build: .docker/php
        container_name: formula_points_php
        volumes:
            - ${SYMFONY_APP}:${WORKDIR}
            - generated_files:${WORKDIR}/var/cache
            - ${SYMFONY_APP}/vendor:${WORKDIR}/vendor:delegated
        working_dir: ${WORKDIR}
        depends_on:
            - mysql

    symfony:
        container_name: formula_points_symfony
        build: .docker/symfony-cli
        working_dir: ${WORKDIR}
        volumes:
            - ${SYMFONY_APP}:${WORKDIR}
        environment:
            - NODEJS_VERSION=${NODEJS_VERSION}

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - "8081:80"
        environment:
            - PMA_ARBITRARY=1

    nginx:
        container_name: formula_points_nginx
        build: .docker/nginx
        volumes:
            - ${SYMFONY_APP}:${WORKDIR}
            - ${NGINX_LOGS}:/var/log/nginx/
        environment:
            - WORKDIR=${WORKDIR}
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
        networks:
            default:
                aliases:
                    - 'dev.formula-points'
